name: Publish Scheduled twits
on:
  schedule: # Run workflow automatically
    - cron: 0/5 * * * * # Runs every hour, on the hour
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@latest
      with:
        node-version: '14.x'
    - run: node index.js
